;;; init.el --- scratch framework init -*- lexical-binding: t; -*-
;;
;; Framework bootstrap. Topical setup lives under `lisp/' as
;; `scratch-<topic>.el' files; this file just dispatches to them and
;; then hands off to the user's literate config in $SCRATCHDIR
;; (default ~/.scratch.d/).

(require 'cl-lib)

(defvar scratch-emacs-dir
  (file-name-directory (or load-file-name buffer-file-name))
  "Path to the scratch framework dir (this repo).")

(defvar scratch-user-dir
  (file-name-as-directory
   (expand-file-name (or (getenv "SCRATCHDIR") "~/.scratch.d")))
  "Path to the user's config dir (analogue of DOOMDIR).")

(defvar scratch-lisp-dir
  (file-name-as-directory (expand-file-name "lisp" scratch-emacs-dir))
  "Path to the framework's `lisp/' directory.")

(add-to-list 'load-path scratch-lisp-dir)

;;; Shell-environment snapshot. `<user-emacs-directory>/env' is generated
;;; by the `scratch env' CLI command and contains a `read'-able list of
;;; `KEY=VALUE' strings captured from the user's shell. Loaded BEFORE
;;; straight (so git / curl / dotnet are findable on PATH) and BEFORE
;;; modules (so LSP servers, formatters, ripgrep are findable). Skip
;;; gracefully when absent -- env capture is opt-in.
(require 'scratch-env)
(scratch-load-envvars-file
 (expand-file-name "env" user-emacs-directory) 'noerror)

;;; straight.el bootstrap (https://github.com/radian-software/straight.el)
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;;; Pin all already-cloned packages to the SHAs in
;;; straight/versions/default.el. The lockfile is generated by
;;; `M-x straight-freeze-versions' (or `scratch freeze' from the shell)
;;; and tracked in git. New packages clone at HEAD; run `scratch freeze'
;;; after adding one to capture its commit.
(let ((versions-file
       (expand-file-name "straight/versions/default.el"
                         (or (bound-and-true-p straight-base-dir)
                             user-emacs-directory))))
  (when (file-exists-p versions-file)
    (straight-thaw-versions)))

;;; use-package, installed and used by default via straight
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

;;; Tell straight to use Emacs's built-in `org' rather than cloning
;;; upstream. This must run BEFORE anything `(require 'org)' (the
;;; tangle step below does), and BEFORE any package that lists
;;; `org' in `Package-Requires' (e.g. org-modern, org-appear) gets
;;; installed -- otherwise straight pulls upstream org as a
;;; transitive dependency, and the two versions clash on first
;;; org-mode buffer.
(straight-use-package '(org :type built-in))

;;; Customize output stays under user-emacs-directory (this framework dir).
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file) (load custom-file))

;;; Framework topical setup
(require 'scratch-modules)    ; scratch! / modulep! macros
(require 'scratch-defaults)   ; recentf, savehist, save-place, file/format defaults
(require 'scratch-keys)       ; general + the `map!' macro (framework-wide)
(require 'scratch-buffer)     ; buffer helpers (scratch/scratch-buffer, ...)
(require 'scratch-code)       ; prog-mode dispatchers (format, ...)
(require 'scratch-window)     ; window numbering + M-N bindings
(require 'scratch-treesit)    ; `scratch-treesit-want' (consumed by :editor tree-sitter)

;;; Literate user config: tangle $SCRATCHDIR/config.org -> config.el +
;;; packages.el on demand, then load the tangled output.
(defun scratch--tangle-if-stale (org-file targets)
  "Re-tangle ORG-FILE when any path in TARGETS is missing or older than it."
  (when (and (file-exists-p org-file)
             (cl-some (lambda (target)
                        (or (not (file-exists-p target))
                            (file-newer-than-file-p org-file target)))
                      targets))
    (require 'org)
    (require 'ob-tangle)
    (let ((org-confirm-babel-evaluate nil)
          (gc-cons-threshold most-positive-fixnum))
      (message "[scratch] tangling %s..." (file-name-nondirectory org-file))
      (org-babel-tangle-file org-file))))

(let ((org      (expand-file-name "config.org"  scratch-user-dir))
      (config   (expand-file-name "config.el"   scratch-user-dir))
      (packages (expand-file-name "packages.el" scratch-user-dir)))
  (condition-case err
      (scratch--tangle-if-stale org (list config packages))
    (error (message "[scratch] tangle failed: %S" err)))
  (when (file-exists-p packages) (load packages nil 'nomessage))
  (when (file-exists-p config)   (load config   nil 'nomessage)))
