;;; lisp/scratch-env.el --- shell-environment loader -*- lexical-binding: t; -*-
;;
;; Reads the env file generated by `scratch env' and applies its KEY=VALUE
;; entries to `process-environment', `exec-path', and `shell-file-name'.
;; Adapted directly from `doom-load-envvars-file' in Doom Emacs.

(defun scratch-load-envvars-file (file &optional noerror)
  "Read and set envvars from FILE.
Returns the list of envvar strings that were loaded. With NOERROR
non-nil, silently no-op when FILE is missing."
  (cond
   ((not (file-exists-p file))
    (unless noerror
      (signal 'file-error (list "No envvar file exists" file))))
   (t
    (with-temp-buffer
      (insert-file-contents file)
      (when-let* ((env (read (current-buffer))))
        (let ((tz (getenv-internal "TZ")))
          (setq-default
           process-environment
           (append env (default-value 'process-environment))
           exec-path
           (append (split-string (getenv "PATH") path-separator t)
                   (list exec-directory))
           shell-file-name
           (or (getenv "SHELL")
               (default-value 'shell-file-name)))
          (when-let* ((newtz (getenv-internal "TZ")))
            (unless (equal tz newtz)
              (set-time-zone-rule newtz))))
        env)))))

(provide 'scratch-env)
;;; scratch-env.el ends here
