;;; scratch-packages.el --- fast-path package activation -*- lexical-binding: t; -*-
;;
;; During `scratch sync', all package autoloads are concatenated into a
;; single `scratch-autoloads.el' file under `user-emacs-directory'.
;; Loading that one file at startup replaces ~148 individual autoload
;; file loads and the per-package build checks that straight-use-package
;; normally performs.
;;
;; The generate step also native-compiles the bundled file (when
;; native-comp is available) so subsequent loads hit the .eln cache.

(require 'cl-lib)

(defvar scratch-autoloads-file
  (expand-file-name "scratch-autoloads.el" user-emacs-directory)
  "Path to the concatenated autoloads file generated by `scratch sync'.")

(defun scratch-packages--generate-autoloads ()
  "Concatenate all package autoloads into `scratch-autoloads-file'.
Intended to be called from `scratch sync' after all packages are
installed and built."
  (let* ((build-dir (expand-file-name
                     "straight/build/"
                     (or (bound-and-true-p straight-base-dir)
                         user-emacs-directory)))
         (pkg-dirs (directory-files build-dir t "\\`[^.]"))
         (autoload-files
          (cl-loop for dir in pkg-dirs
                   for name = (file-name-nondirectory dir)
                   for al = (expand-file-name
                             (format "%s-autoloads.el" name) dir)
                   when (file-exists-p al) collect al)))
    (with-temp-file scratch-autoloads-file
      (insert ";;; scratch-autoloads.el --- bundled autoloads "
              "(generated by scratch sync) -*- lexical-binding: t; -*-\n")
      (insert ";; This file is regenerated by `scratch sync'. Do not edit.\n\n")
      ;; load-path entries
      (insert ";; load-path setup\n")
      (dolist (dir pkg-dirs)
        (when (file-directory-p dir)
          (insert (format "(add-to-list 'load-path %S)\n" dir))
          (when (directory-files dir nil "-theme\\.el\\'" t)
            (insert (format "(add-to-list 'custom-theme-load-path %S)\n" dir)))))
      (insert "\n;; autoloads\n")
      ;; Concatenate autoload file contents, stripping local-variable blocks
      (dolist (file autoload-files)
        (insert (format "\n;;; --- %s ---\n" (file-name-nondirectory file)))
        (insert
         (with-temp-buffer
           (insert-file-contents file)
           (goto-char (point-min))
           (when (re-search-forward (concat "^;; Local " "Variables:") nil t)
             (delete-region (line-beginning-position) (point-max)))
           (buffer-string))))
      (insert "\n(provide 'scratch-autoloads)\n"
              ";;; scratch-autoloads.el ends here\n"))
    (message "[scratch] Generated %s (%d packages)"
             scratch-autoloads-file (length autoload-files))
    ;; Byte-compile for faster loading (suppress upstream docstring warnings)
    (message "[scratch] Byte-compiling autoloads...")
    (let ((byte-compile-warnings '(not docstrings free-vars)))
      (byte-compile-file scratch-autoloads-file))
    ;; Native-compile if available
    (when (and (fboundp 'native-compile-async)
               (not (getenv "SCRATCH_SKIP_NATIVECOMP")))
      (message "[scratch] Native-compiling autoloads (async)...")
      (native-compile-async scratch-autoloads-file nil nil))))

(defun scratch-packages-load-autoloads ()
  "Load the bundled autoloads file if it exists.
Returns non-nil if the fast path was used."
  (when (file-exists-p scratch-autoloads-file)
    (load scratch-autoloads-file nil 'nomessage 'nosuffix)
    t))

(provide 'scratch-packages)
;;; scratch-packages.el ends here
